const {test, expect} = require('@playwright/test');
const path = require('path');
const sample = name => path.resolve(__dirname, `../../samples/${name}.pdf`);

async function upload(page, name) {
  await page.getByRole('button', {name: 'New document'}).click();
  await page.locator('#file').setInputFiles(sample(name));
  await page.getByRole('button', {name: 'Upload & process'}).click();
}

test('authenticated upload, correction, audit, rejection and safe failure retry', async ({page, browser}) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/demo');
  await expect(page.getByRole('heading', {name: 'Welcome to Claim Studio'})).toBeVisible();
  await page.getByLabel('Demo password').fill(process.env.BROWSER_PASSWORD || 'browser-synthetic-only');
  await page.getByRole('button', {name: 'Open workspace'}).click();
  await expect(page.getByRole('heading', {name: 'Start with a synthetic document'})).toBeVisible();
  await upload(page, 'valid');
  await expect(page.locator('#state')).toHaveText('READY', {timeout: 20000});
  await expect(page.locator('#risk-level')).toHaveText('LOW');
  await page.getByLabel('Reason for risk acknowledgment').fill('Checked the synthetic evidence.');
  await page.getByRole('button', {name: 'Record risk acknowledgment'}).click();
  await expect(page.locator('#risk-acknowledgment')).toContainText('Computed risk is unchanged');
  await page.getByRole('button', {name: 'Refresh risk assessment', exact: true}).click();
  await expect(page.locator('#risk-level')).toHaveText('LOW');
  await expect(page.locator('#fields')).toContainText('42.50');
  await expect(page.locator('#reasoning')).toContainText('no live OCR');
  await page.screenshot({path: path.resolve(__dirname, '../../docs/screenshots/results.png'), fullPage: true});
  await upload(page, 'review');
  await expect(page.locator('#state')).toHaveText('REVIEW REQUIRED', {timeout: 20000});
  await expect(page.locator('#risk-level')).toHaveText('INSUFFICIENT DATA');
  await expect(page.locator('#issues')).toContainText('Total amount is required');
  await page.getByLabel('Review decision').selectOption('correct');
  await page.getByLabel('Billed amount (USD)').fill('48.75');
  await page.getByLabel('Reason for your decision').fill('Checked the synthetic source; recorded corrected amount.');
  await page.getByRole('button', {name: 'Save review decision'}).click();
  await expect(page.locator('#state')).toHaveText('READY');
  await expect(page.locator('#fields')).toContainText('48.75');
  await expect(page.locator('#history')).toContainText('CORRECT');
  await page.locator('#history summary').click();
  await expect(page.locator('#history pre')).toContainText('48.75');
  await page.screenshot({path: path.resolve(__dirname, '../../docs/screenshots/review.png'), fullPage: true});
  const stranger = await browser.newContext();
  const response = await stranger.request.get('/claims');
  expect(response.status()).toBe(401);
  await stranger.close();
  await upload(page, 'review');
  await expect(page.locator('#state')).toHaveText('REVIEW REQUIRED', {timeout: 20000});
  await page.getByLabel('Review decision').selectOption('reject');
  await page.getByLabel('Reason for your decision').fill('Rejected this synthetic incomplete document.');
  await page.getByRole('button', {name: 'Save review decision'}).click();
  await expect(page.locator('#state')).toHaveText('REJECTED');
  await upload(page, 'failure');
  await expect(page.locator('#state')).toHaveText('FAILED', {timeout: 20000});
  await expect(page.getByRole('button', {name: 'Retry processing'})).toBeVisible();
  let releaseRetry;
  const retryGate = new Promise(resolve => { releaseRetry = resolve; });
  await page.route('**/documents/*/extract', async route => {
    await retryGate;
    await route.continue();
  });
  await page.getByRole('button', {name: 'Retry processing'}).click();
  await expect(page.getByRole('button', {name: 'Sign out'})).toBeDisabled();
  releaseRetry();
  await expect(page.getByRole('button', {name: 'Sign out'})).toBeEnabled();
  await page.unroute('**/documents/*/extract');
  await expect(page.locator('#state')).toHaveText('FAILED', {timeout: 20000});
  await page.getByRole('button', {name: 'My documents'}).click();
  await expect(page.locator('.claim-row')).toHaveCount(4);
  await page.getByRole('button', {name: 'Sign out'}).click();
  await expect(page.getByRole('heading', {name: 'Welcome to Claim Studio'})).toBeVisible();
  expect(errors).toEqual([]);
});

test('risk explanations, HIGH acknowledgment, history and stale conflict recovery', async ({page}) => {
  await page.goto('/demo');
  await page.getByLabel('Demo password').fill(process.env.BROWSER_PASSWORD || 'browser-synthetic-only');
  await page.getByRole('button', {name: 'Open workspace'}).click();
  await upload(page, 'review');
  await expect(page.locator('#state')).toHaveText('REVIEW REQUIRED', {timeout: 20000});
  await page.getByLabel('Review decision').selectOption('correct');
  await page.getByLabel('Billed amount (USD)').fill('100001');
  await page.getByLabel('Reason for your decision').fill('Confirmed synthetic amount.');
  await page.getByRole('button', {name: 'Save review decision'}).click();
  await expect(page.locator('#state')).toHaveText('READY');
  await expect(page.locator('#risk-level')).toHaveText('HIGH');
  await expect(page.locator('#risk-signals')).toContainText('illustrative high review threshold');
  await page.getByRole('button', {name: 'Show assessment history'}).click();
  await expect(page.locator('#risk-history details')).toHaveCount(2);
  await page.route('**/risk/acknowledgments', route => route.fulfill({status: 409, contentType: 'application/json', body: JSON.stringify({code:'stale_assessment',message:'Refresh the current risk assessment'})}));
  await page.getByLabel('Reason for risk acknowledgment').fill('Investigated synthetic rule.');
  await page.getByRole('button', {name: 'Record risk acknowledgment'}).click();
  await expect(page.locator('#message')).toContainText('stale_assessment');
  await expect(page.locator('#risk-level')).toHaveText('HIGH');
  await page.unroute('**/risk/acknowledgments');
  await page.getByRole('button', {name: 'Record risk acknowledgment'}).click();
  await expect(page.locator('#risk-acknowledgment')).toContainText('Computed risk is unchanged');
  await expect(page.locator('#risk-level')).toHaveText('HIGH');
});
