"""index exact document risk matching

Revision ID: 968da3f6918e
Revises: a1fb3ff0cf40
"""

from alembic import op

revision = "968da3f6918e"
down_revision = "a1fb3ff0cf40"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_document_sha_claim", "documents", ["sha256", "claim_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_document_sha_claim", table_name="documents")
    # ### end Alembic commands ###
