"""immutable risk assessments and acknowledgments

Revision ID: a1fb3ff0cf40
Revises: b61ceaf00211
"""

import sqlalchemy as sa
from alembic import op

revision = "a1fb3ff0cf40"
down_revision = "b61ceaf00211"
branch_labels = None
depends_on = None


def upgrade():
    op.create_unique_constraint(
        "uq_document_claim_identity", "documents", ["claim_id", "document_id"]
    )
    op.create_unique_constraint(
        "uq_extraction_document_identity", "extraction_results", ["extraction_id", "document_id"]
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "risk_assessments",
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("extraction_id", sa.UUID(), nullable=False),
        sa.Column("claim_version", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=30), nullable=False),
        sa.Column("policy_version", sa.String(length=50), nullable=False),
        sa.Column("signals", sa.JSON(), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("context_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("context_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "level IN ('LOW','MEDIUM','HIGH','INSUFFICIENT_DATA')", name="ck_risk_level"
        ),
        sa.CheckConstraint("claim_version >= 1 AND revision >= 1", name="ck_risk_versions"),
        sa.CheckConstraint(
            "length(input_fingerprint) = 64 AND length(context_fingerprint) = 64",
            name="ck_risk_fingerprints",
        ),
        sa.ForeignKeyConstraint(
            ["claim_id", "document_id"],
            ["documents.claim_id", "documents.document_id"],
            name="fk_risk_claim_document",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_id", "document_id"],
            ["extraction_results.extraction_id", "extraction_results.document_id"],
            name="fk_risk_extraction_document",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("assessment_id"),
        sa.UniqueConstraint("claim_id", "revision", name="uq_risk_claim_revision"),
    )
    op.create_index("ix_risk_level", "risk_assessments", ["level"], unique=False)
    op.create_table(
        "risk_acknowledgments",
        sa.Column("acknowledgment_id", sa.UUID(), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.String(length=2000), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(reason)) >= 1", name="ck_risk_ack_reason"),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["risk_assessments.assessment_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("acknowledgment_id"),
        sa.UniqueConstraint("assessment_id", "actor_id", name="uq_risk_ack_actor"),
    )
    op.execute("""
        CREATE FUNCTION reject_risk_update() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'Risk history is immutable';
        END;
        $$;
    """)
    for table in ("risk_assessments", "risk_acknowledgments"):
        op.execute(
            f"CREATE TRIGGER immutable_risk_update BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION reject_risk_update()"
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("risk_acknowledgments")
    op.drop_index("ix_risk_level", table_name="risk_assessments")
    op.drop_table("risk_assessments")
    op.execute("DROP FUNCTION reject_risk_update()")
    op.drop_constraint("uq_extraction_document_identity", "extraction_results", type_="unique")
    op.drop_constraint("uq_document_claim_identity", "documents", type_="unique")
    # ### end Alembic commands ###
